name: Build N64Recomp on Windows

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      # Step 1: Checkout the repository with GitHub Actions v4
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive 
          
      # Step 2: Setup cmake
      - name: get-cmake
        uses: lukka/get-cmake@v3.31.6
  
      # Step 3: Create build directory
      - name: Create build directory
        run: mkdir build

      # Step 4: Configure project with Visual Studio 2022
      - name: Configure project with CMake (Visual Studio 2022)
        run: |
          cd build
          cmake -G "Visual Studio 17 2022" ..

      # Step 5: Build the project
      - name: Build project
        run: |
          cd build
          cmake --build . --config Release

      # Step 6: Upload all .exe files from the build folder as artifacts
      - name: Upload build artifacts (all .exe files)
        uses: actions/upload-artifact@v4
        with:
          name: n64-recompiled-exes
          path: build/Release/*.exe  # Adjust if the .exe files are in a different subdirectory
